FROM node:13.12.0-alpine as builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app
COPY index.js /app/index.js
COPY .env /app/.env
COPY assets /app/assets
copy repos /app/repos

RUN npm install

EXPOSE 8002