
##############################################################
# Requetes http 
##############################################################
### Définition des variables globales
@hostname = http://localhost:8002/api

####
#### Get list de connections 
#### 
GET {{hostname}}/ HTTP/1.1
X-API-Key: cqen-api-test
Content-Type: application/json

####
