version: "3"

services:

  # ReactJS APP Verifier 
  simplex-app-dev: 
    image: simplex-application-dev
    environment: 
      - APP_PORT:8001
    ports: 
      - 8001:8001
    networks: 
      - dts-vc-app
    command: [
      "npm", "start"
    ]

    # ReactJS API Verifier 
  simplex-api-dev: 
    image: simplex-application-api-dev
    environment:
      - API_PORT:8002
    ports: 
      #- ${VERIFIER_API_PORT}:${VERIFIER_API_PORT}
      - 8002:8002
    networks: 
      - dts-vc-api
    command: [
      "npm", "start"
    ]

networks:
  dts-vc-app:
  dts-vc-api: